spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: vehicle-parameters-service
          uri: lb:http://VEHICLE-PARAMETERS-SERVICE
          predicates:
            -  Path=/api/vehicleParameters/**
        - id: hr-configurations-service
          uri: lb:http://HR-CONFIGURATIONS-SERVICE
          predicates:
            -  Path=/api/hrConfigurations/**
        - id: locations-service
          uri: lb:http://LOCATIONS-SERVICE
          predicates:
            -  Path=/api/locations/**
        - id: service1
          uri: lb://service1
          predicates:
            -  Path=/service/test/**

server:
  port: 8222


